export const application = {
  name: "Vocab Lexic",
  longName: "Vocab Lexic",
  description: "A fun Wordle game clone!",
  footerLabel: "© 2024 Vocab Lexic by OnlineJobs!. All rights reserved.",
};

export const lenguaje = {
  spain: "SPAIN",
  cata: "CATA",
  usa: "US",
  fr: "FR",
  mexico: "MEXICO",
};

export const labels = {
  cata: {
    footerLabel: "© 2024 Vocab Lexic per OnlineJobs!",
    win: "Has guanyat!",
    winDescription: "Has trobat la solució",
    loose: "Has perdut!",
    looseDescription: "Potser la pròxima vegada!",
    input: "Introdueix la paraula",
    noMoreTryes: "No tens més oportunitats.",
    alreadyTested: "Ja has provat aquesta paraula.",
    fiveLetters: "Ha de tenir 5 lletres.",
  },
  usa: {
    footerLabel: "© 2024 Vocab Lexic by OnlineJobs!. All rights reserved.",
    win: "You Win!",
    winDescription: "You find the solution",
    loose: "You Loose!",
    looseDescription: "May be next time!",
    input: "Enter the word",
    noMoreTryes: "No more chances.",
    alreadyTested: "You've already tested that word.",
    fiveLetters: "It must have 5 letters.",
  },
  spain: {
    footerLabel: "© 2024 Vocab Lexic de OnlineJobs!",
    win: "Ganaste",
    winDescription: "Encontraste la solucion.",
    loose: "Perdiste!",
    looseDescription: "La proxima vas a ganar!",
    input: "Introduce la palabra",
    noMoreTryes: "No tiene mas chances.",
    alreadyTested: "Ya probaste esa palabra.",
    fiveLetters: "Debe tener 5 letras",
  },
  mexico: {
    footerLabel: "© 2024 Vocab Lexic de OnlineJobs, ¡puro sabor mexicano!",
    win: "¡Ganaste, campeón!",
    winDescription: "¡Le atinaste a la solución, qué chido!",
    loose: "¡Perdiste, amigo!",
    looseDescription: "¡Ánimo, la próxima sí la haces!",
    input: "Introduce la palabra aquí",
    noMoreTryes: "Ya no tienes más intentos, ¡buena suerte la próxima!",
    alreadyTested: "Esa palabra ya la probaste, ¡intenta otra!",
    fiveLetters: "La palabra debe tener 5 letras, ¡échale ganas!",
  },
  france: {
    footerLabel: "© 2024 Vocab Lexic de OnlineJobs!",
    win: "Tu as gagné",
    winDescription: "Tu as trouvé la solution.",
    loose: "Tu as perdu!",
    looseDescription: "La prochaine fois, tu gagneras!",
    input: "Entrez la motoné",
    noMoreTryes: "Vous n'avez plus de chances.",
    alreadyTested: "Vous avez déjà testé ce mot.",
    fiveLetters: "Il doit avoir 5 lettres.",
  },
};
